"""Generated catalogue rows — real Indian brands, realistic prices, all tiles covered."""

from __future__ import annotations

# (name, brand, category, price, mrp, unit, available_in)
# available_in: None -> all three locations

_ALL = None
_DELHI = ["Sarjapur", "Whitefield", "Delhi NCR"]
_WF_DELHI = ["Whitefield", "Delhi NCR"]

GENERATED_PRODUCTS: list[tuple] = [
    # --- Demo-critical (order fixed; matched by build_catalog household SKUs) ---
    ("Happilo Premium Dry Fruits Mix", "Happilo", "Dry Fruits & Cereals", 449, 499, "500 g", _ALL),
    ("Amul Taaza Homogenised Toned Milk", "Amul", "Dairy, Bread & Eggs", 54, 54, "1 L", _ALL),
    ("Aashirvaad Superior MP Whole Wheat Atta", "Aashirvaad", "Atta, Rice & Dal", 265, 280, "5 kg", _ALL),
    ("Onion (Pyaz)", "Fresh", "Vegetables & Fruits", 32, 40, "1 kg", _ALL),
    ("Britannia Brown Bread", "Britannia", "Dairy, Bread & Eggs", 45, 50, "400 g", _ALL),
    ("Table White Eggs", "Fresho", "Dairy, Bread & Eggs", 72, 78, "6 pcs", _ALL),
    ("Cadbury Celebrations Premium Assorted Gift Pack", "Cadbury", "E-Gifts Store", 399, 449, "1 pack", _ALL),
    ("Gift wrapping paper roll metallic gold", "Archies", "E-Gifts Store", 149, 199, "1 roll", _ALL),
    ("Roli chawal combo pack", "Patanjali", "Spiritual Needs", 49, 59, "1 pack", _ALL),
    ("Clay diyas pack of 12", "Local", "Spiritual Needs", 89, 99, "12 pcs", _ALL),
    ("Cotton double bedsheet floral", "Bombay Dyeing", "Home & Lifestyle", 599, 799, "1 pc", _WF_DELHI),
    ("Soft fiber pillow", "Wakefit", "Home & Lifestyle", 349, 449, "1 pc", _WF_DELHI),
    ("Cotton bath towel large", "Trident", "Bath & Body", 299, 399, "1 pc", _WF_DELHI),
    ("Plastic bucket 15 L blue", "Milton", "Kitchenware & Appliances", 189, 229, "1 pc", _WF_DELHI),
    ("Plastic mug 1 L", "Cello", "Kitchenware & Appliances", 79, 99, "1 pc", _WF_DELHI),
    ("Floor mop with stick", "Gala", "Cleaners & Repellents", 249, 299, "1 pc", _WF_DELHI),
    ("Pedal dustbin 10 L", "Nilkamal", "Home & Lifestyle", 449, 549, "1 pc", _WF_DELHI),
    ("Stainless steel pet bowl", "Super Pet", "Pet Store", 199, 249, "1 pc", _ALL),
    ("Cat litter scoop", "Super Pet", "Pet Store", 59, 79, "1 pc", _ALL),
    ("Kashmir Apple", "Fresh", "Vegetables & Fruits", 120, 140, "4 pcs", _ALL),
    ("Prestige induction compatible cookware set", "Prestige", "Kitchenware & Appliances", 1299, 1599, "3 pcs", _ALL),
    ("Anchor 6 A 3-pin plug top", "Anchor", "Electronics", 99, 120, "1 pc", _ALL),
    ("Fortune refined sunflower oil", "Fortune", "Oil, Ghee & Masala", 145, 160, "1 L", _ALL),
    ("Tata Sampann unpolished moong dal", "Tata Sampann", "Atta, Rice & Dal", 89, 99, "500 g", _ALL),
    ("Amul Salted Butter", "Amul", "Dairy, Bread & Eggs", 58, 62, "100 g", _ALL),
    # --- Grocery & Kitchen fill ---
    ("Banana Robusta", "Fresh", "Vegetables & Fruits", 48, 55, "6 pcs", _ALL),
    ("Tomato Hybrid", "Fresh", "Vegetables & Fruits", 28, 35, "500 g", _ALL),
    ("Potato (Aloo)", "Fresh", "Vegetables & Fruits", 35, 42, "1 kg", _ALL),
    ("Cauliflower", "Fresh", "Vegetables & Fruits", 39, 49, "1 pc", _ALL),
    ("India Gate Basmati Rice Classic", "India Gate", "Atta, Rice & Dal", 399, 450, "5 kg", _ALL),
    ("Daawat Pulav Basmati Rice", "Daawat", "Atta, Rice & Dal", 110, 125, "1 kg", _ALL),
    ("Rajdhani Toor Dal", "Rajdhani", "Atta, Rice & Dal", 149, 165, "1 kg", _ALL),
    ("Ghee Amul Pure", "Amul", "Oil, Ghee & Masala", 320, 340, "500 ml", _ALL),
    ("MDH Garam Masala", "MDH", "Oil, Ghee & Masala", 85, 95, "100 g", _ALL),
    ("Maggi 2-Minute Noodles Masala", "Maggi", "Instant Food", 56, 60, "4 pcs", _ALL),
    ("Amul Masti Curd", "Amul", "Dairy, Bread & Eggs", 35, 38, "400 g", _ALL),
    ("Mother Dairy Classic Curd", "Mother Dairy", "Dairy, Bread & Eggs", 34, 36, "400 g", _ALL),
    ("Parle-G Gold Glucose Biscuits", "Parle", "Bakery & Biscuits", 30, 35, "600 g", _ALL),
    ("Sunfeast Dark Fantasy Choco Fills", "Sunfeast", "Bakery & Biscuits", 110, 125, "300 g", _ALL),
    ("Kaju Katli premium", "Haldiram's", "Sweets & Chocolates", 349, 399, "250 g", _ALL),
    ("Happilo Roasted Mixed Nuts", "Happilo", "Dry Fruits & Cereals", 299, 349, "200 g", _ALL),
    ("Real Activ orange juice", "Real", "Drinks & Juices", 95, 110, "1 L", _ALL),
    ("Tropicana guava delight", "Tropicana", "Drinks & Juices", 99, 115, "1 L", _ALL),
    ("Lipton Yellow Label tea", "Lipton", "Tea, Coffee & Milk Drinks", 145, 160, "250 g", _ALL),
    ("Nescafe Classic instant coffee", "Nescafe", "Tea, Coffee & Milk Drinks", 320, 350, "100 g", _ALL),
    ("Lay's India's Magic Masala", "Lay's", "Chips & Namkeen", 20, 20, "52 g", _ALL),
    ("Haldiram's Bhujia Sev", "Haldiram's", "Chips & Namkeen", 55, 60, "400 g", _ALL),
    ("Kissan tomato ketchup", "Kissan", "Sauces & Spreads", 85, 95, "950 g", _ALL),
    ("Nutella hazelnut spread", "Nutella", "Sauces & Spreads", 349, 399, "350 g", _ALL),
    ("Amul Ice Cream Cup Vanilla", "Amul", "Ice Creams & More", 40, 45, "100 ml", _ALL),
    ("Kwality Walls Cornetto butterscotch", "Kwality Walls", "Ice Creams & More", 45, 50, "1 pc", _ALL),
    ("Fresh chicken curry cut", "Licious", "Chicken, Meat & Fish", 189, 210, "500 g", _ALL),
    ("Rohu fish steak", "Fresh", "Chicken, Meat & Fish", 249, 279, "500 g", _ALL),
    ("Prestige non-stick tawa", "Prestige", "Kitchenware & Appliances", 599, 699, "1 pc", _ALL),
    ("Milton casseroles set", "Milton", "Kitchenware & Appliances", 799, 899, "3 pcs", _ALL),
    # --- Beauty & Personal Care ---
    ("Dove cream beauty bathing bar", "Dove", "Bath & Body", 89, 99, "3 x 125 g", _ALL),
    ("Lux soft touch soap", "Lux", "Bath & Body", 65, 72, "4 x 100 g", _ALL),
    ("Head & Shoulders anti-dandruff shampoo", "Head & Shoulders", "Hair", 299, 349, "340 ml", _ALL),
    ("Pantene hair fall control conditioner", "Pantene", "Hair", 249, 279, "180 ml", _ALL),
    ("Pond's light moisturiser", "Pond's", "Skin & Face", 149, 169, "150 ml", _ALL),
    ("Lakme 9to5 nail color", "Lakme", "Beauty & Cosmetics", 199, 225, "1 pc", _ALL),
    ("Whisper Ultra sanitary pads", "Whisper", "Feminine Hygiene", 165, 185, "14 pcs", _ALL),
    ("Pampers baby dry pants", "Pampers", "Baby Care", 599, 649, "24 pcs", _ALL),
    ("Dabur Honitus cough syrup", "Dabur", "Health & Pharma", 125, 140, "100 ml", _ALL),
    ("Durex extra thin condoms", "Durex", "Sexual Wellness", 199, 220, "10 pcs", _ALL),
    # --- Household Essentials ---
    ("Room freshener lavender spray", "Odonil", "Cleaners & Repellents", 149, 175, "220 ml", _ALL),
    ("Lizol citrus floor cleaner", "Lizol", "Cleaners & Repellents", 189, 210, "975 ml", _ALL),
    ("Pet-safe floor cleaner", "BearHugs", "Cleaners & Repellents", 249, 299, "1 L", _ALL),
    ("Goodknight mosquito repellent refill", "Goodknight", "Cleaners & Repellents", 75, 85, "1 pc", _ALL),
    ("Scotch-Brite lint roller", "Scotch-Brite", "Home & Lifestyle", 199, 249, "1 pc", _ALL),
    ("Philips 9W LED bulb", "Philips", "Electronics", 99, 120, "1 pc", _ALL),
    ("Classmate notebook single line", "Classmate", "Stationery & Games", 45, 50, "1 pc", _ALL),
    ("Monopoly board game", "Hasbro", "Stationery & Games", 499, 599, "1 pc", _ALL),
    # --- Dedicated Stores ---
    ("Agarbatti masala incense sticks", "Cycle", "Spiritual Needs", 55, 65, "1 pack", _ALL),
    ("Brass pooja thali small", "Local", "Spiritual Needs", 299, 349, "1 pc", _ALL),
    ("Peppa Pig soft toy", "Peppa Pig", "Toy Store", 399, 499, "1 pc", _ALL),
    ("Diary of a Wimpy Kid book", "Puffin", "Book Store", 299, 350, "1 pc", _ALL),
    ("Silver finish earrings pair", "Zaveri", "Jewellery Store", 199, 249, "1 pair", _ALL),
    ("Allen Solly crew neck T-shirt", "Allen Solly", "Fashion Basics", 599, 799, "1 pc", _ALL),
    ("Yonex badminton shuttlecock nylon", "Yonex", "Sports Store", 349, 399, "6 pcs", _ALL),
    ("Camel sketch pen set", "Camel", "Hobby Store", 120, 140, "1 set", _ALL),
    ("Skybags cabin trolley 55 cm", "Skybags", "Travel Store", 2499, 2999, "1 pc", _DELHI),
    ("Crocin advance tablet strip", "Crocin", "Pharma Store", 35, 40, "15 tabs", _ALL),
    ("Amul ice cream family pack butterscotch", "Amul", "Ice Cream Store", 199, 225, "700 ml", _ALL),
    # --- Delhi assortment extras (depth evidence) ---
    ("Organic quinoa", "True Elements", "Dry Fruits & Cereals", 349, 399, "500 g", ["Delhi NCR"]),
    ("Imported avocado", "Fresh", "Vegetables & Fruits", 189, 220, "2 pcs", ["Delhi NCR"]),
    ("Le Creuset style cast iron pan", "Wonderchef", "Kitchenware & Appliances", 1899, 2199, "1 pc", ["Delhi NCR"]),
    ("Diptyque style room diffuser", "Bella Vita", "Home & Lifestyle", 599, 699, "1 pc", ["Delhi NCR"]),
    ("Artisan sourdough loaf", "The Baker's Dozen", "Bakery & Biscuits", 149, 175, "400 g", ["Delhi NCR"]),
    ("Cold brew coffee bottle", "Blue Tokai", "Drinks & Juices", 180, 200, "250 ml", ["Delhi NCR"]),
    ("Mezze hummus tub", "Tabouleh", "Instant Food", 199, 229, "200 g", ["Delhi NCR"]),
    ("Kombucha ginger lemon", "Atmosphere", "Drinks & Juices", 149, 169, "250 ml", ["Delhi NCR"]),
    ("Designer diya set ceramic", "Local", "Spiritual Needs", 249, 299, "6 pcs", ["Delhi NCR"]),
    ("Premium gift hamper dry fruits", "Nutraj", "E-Gifts Store", 899, 999, "1 pack", ["Delhi NCR"]),
    ("Memory foam bath mat", "Spaces", "Bath & Body", 399, 499, "1 pc", ["Delhi NCR"]),
    ("Smart LED strip 5m", "Wipro", "Electronics", 799, 999, "1 pc", ["Delhi NCR"]),
    ("Yoga mat 6mm", "Strauss", "Sports Store", 449, 549, "1 pc", ["Delhi NCR"]),
    ("Cat wet food variety pack", "Sheba", "Pet Store", 399, 449, "12 x 85 g", ["Delhi NCR"]),
    ("Paan masala mouth freshener", "Rajnigandha", "Paan Corner", 45, 50, "1 pack", ["Delhi NCR"]),
    ("Veeba mayo eggless", "Veeba", "Sauces & Spreads", 89, 99, "250 g", _ALL),
    ("Bambino vermicelli roasted", "Bambino", "Instant Food", 42, 48, "400 g", _ALL),
    ("Saffola oats masala", "Saffola", "Dry Fruits & Cereals", 199, 220, "500 g", _ALL),
    ("Bru instant coffee sachets", "Bru", "Tea, Coffee & Milk Drinks", 165, 180, "20 sachets", _ALL),
    ("Cadbury Dairy Milk silk", "Cadbury", "Sweets & Chocolates", 85, 90, "60 g", _ALL),
    ("Paperboat aamras", "Paper Boat", "Drinks & Juices", 45, 50, "250 ml", _ALL),
    ("Tata Tea Premium", "Tata Tea", "Tea, Coffee & Milk Drinks", 210, 230, "500 g", _ALL),
    ("Bingo mad angles", "Bingo", "Chips & Namkeen", 20, 20, "66 g", _ALL),
    ("Pringles original", "Pringles", "Chips & Namkeen", 99, 110, "107 g", _ALL),
    ("Kellogg's chocos", "Kellogg's", "Dry Fruits & Cereals", 185, 199, "375 g", _ALL),
    ("Dettol antiseptic liquid", "Dettol", "Cleaners & Repellents", 120, 135, "550 ml", _ALL),
    ("Harpic power plus toilet cleaner", "Harpic", "Cleaners & Repellents", 99, 110, "500 ml", _ALL),
    ("Vim dishwash gel lemon", "Vim", "Cleaners & Repellents", 85, 95, "500 ml", _ALL),
    ("Surf Excel easy wash", "Surf Excel", "Cleaners & Repellents", 189, 210, "1 kg", _ALL),
    ("Comfort fabric conditioner", "Comfort", "Cleaners & Repellents", 145, 160, "860 ml", _ALL),
    ("Godrej aer pocket bathroom", "Godrej", "Cleaners & Repellents", 55, 65, "1 pc", _ALL),
    ("Origami tissue box", "Origami", "Home & Lifestyle", 89, 99, "200 pulls", _ALL),
    ("Cello Opalware dinner set", "Cello", "Kitchenware & Appliances", 999, 1199, "19 pcs", _ALL),
    ("Butterfly stainless steel lunch box", "Butterfly", "Kitchenware & Appliances", 449, 499, "3 pcs", _ALL),
    ("Pigeon electric kettle 1.5 L", "Pigeon", "Kitchenware & Appliances", 699, 799, "1 pc", _ALL),
    ("Wipro 3-burner gas stove", "Wipro", "Kitchenware & Appliances", 2499, 2799, "1 pc", ["Delhi NCR"]),
    ("OnePlus Bullets wireless Z2", "OnePlus", "Electronics", 1999, 2299, "1 pc", _ALL),
    ("Duracell AA batteries 4 pack", "Duracell", "Electronics", 149, 165, "4 pcs", _ALL),
    ("Faber-Castell color pencil set", "Faber-Castell", "Stationery & Games", 199, 225, "24 shades", _ALL),
    ("UNO playing cards", "Mattel", "Stationery & Games", 149, 175, "1 pack", _ALL),
    ("Hot wheels basic car", "Hot Wheels", "Toy Store", 99, 125, "1 pc", _ALL),
    ("Sudha Murty short stories", "Puffin", "Book Store", 199, 250, "1 pc", _ALL),
    ("Gold plated bangle set", "Zaveri", "Jewellery Store", 499, 599, "1 set", _ALL),
    ("Peter England formal shirt", "Peter England", "Fashion Basics", 899, 1099, "1 pc", _ALL),
    ("Nivia football size 5", "Nivia", "Sports Store", 499, 599, "1 pc", _ALL),
    ("Camel acrylic paint set", "Camel", "Hobby Store", 249, 299, "12 tubes", _ALL),
    ("Wildcraft travel pouch", "Wildcraft", "Travel Store", 399, 449, "1 pc", _ALL),
    ("Volini pain relief spray", "Volini", "Pharma Store", 175, 195, "60 g", _ALL),
    ("Cornetto disc black forest", "Kwality Walls", "Ice Cream Store", 50, 55, "1 pc", _ALL),
    ("Amul cheese slices", "Amul", "Dairy, Bread & Eggs", 115, 125, "200 g", _ALL),
    ("Britannia cheese spread", "Britannia", "Dairy, Bread & Eggs", 95, 105, "200 g", _ALL),
    ("Epigamia greek yogurt natural", "Epigamia", "Dairy, Bread & Eggs", 65, 70, "130 g", _ALL),
    ("English cucumber", "Fresh", "Vegetables & Fruits", 45, 55, "500 g", _ALL),
    ("Broccoli", "Fresh", "Vegetables & Fruits", 69, 79, "500 g", _ALL),
    ("Red bell pepper", "Fresh", "Vegetables & Fruits", 89, 99, "500 g", _ALL),
    ("Baby corn packet", "Fresh", "Vegetables & Fruits", 55, 65, "200 g", _ALL),
    ("Basil leaves bunch", "Fresh", "Vegetables & Fruits", 39, 45, "1 bunch", _ALL),
    ("Organic brown rice", "24 Mantra", "Atta, Rice & Dal", 189, 210, "1 kg", _ALL),
    ("Organic chana dal", "24 Mantra", "Atta, Rice & Dal", 95, 105, "500 g", _ALL),
    ("Saffola gold oil blend", "Saffola", "Oil, Ghee & Masala", 175, 190, "1 L", _ALL),
    ("Catch black pepper powder", "Catch", "Oil, Ghee & Masala", 89, 99, "100 g", _ALL),
    ("Everest tikhalal chilli powder", "Everest", "Oil, Ghee & Masala", 75, 85, "100 g", _ALL),
    ("McCain french fries", "McCain", "Instant Food", 99, 110, "420 g", _ALL),
    ("Knorr soup tomato", "Knorr", "Instant Food", 55, 60, "50 g", _ALL),
    ("Yippee noodles magic masala", "Sunfeast", "Instant Food", 48, 52, "4 pcs", _ALL),
    ("MTR rava idli mix", "MTR", "Instant Food", 65, 72, "500 g", _ALL),
    ("Bikaji aloo bhujia", "Bikaji", "Chips & Namkeen", 45, 50, "400 g", _ALL),
    ("Too Yumm karare", "Too Yumm", "Chips & Namkeen", 20, 20, "55 g", _ALL),
    ("Ferrero Rocher 16 pieces", "Ferrero", "Sweets & Chocolates", 449, 499, "200 g", _ALL),
    ("Nestle KitKat 4 finger", "Nestle", "Sweets & Chocolates", 25, 25, "38 g", _ALL),
    ("Raw pressery cold pressed juice", "Raw", "Drinks & Juices", 99, 110, "250 ml", _ALL),
    ("Bisleri packaged water 1 L", "Bisleri", "Drinks & Juices", 20, 20, "1 L", _ALL),
    ("Red Bull energy drink", "Red Bull", "Drinks & Juices", 125, 125, "250 ml", _ALL),
    ("Tata Gold tea leaves", "Tata Tea", "Tea, Coffee & Milk Drinks", 420, 450, "1 kg", _ALL),
    ("Starbucks by Nespresso capsules", "Starbucks", "Tea, Coffee & Milk Drinks", 499, 549, "10 pcs", ["Delhi NCR"]),
    ("Colgate maxfresh toothpaste", "Colgate", "Bath & Body", 99, 110, "150 g", _ALL),
    ("Fiama gel bar peach", "Fiama", "Bath & Body", 89, 99, "3 x 125 g", _ALL),
    ("Clinic Plus strong & long shampoo", "Clinic Plus", "Hair", 99, 110, "340 ml", _ALL),
    ("Indulekha bringha oil", "Indulekha", "Hair", 432, 450, "100 ml", _ALL),
    ("Garnier micellar water", "Garnier", "Skin & Face", 175, 195, "125 ml", _ALL),
    ("Maybelline colossal kajal", "Maybelline", "Beauty & Cosmetics", 199, 220, "1 pc", _ALL),
    ("Stayfree secure cottony soft", "Stayfree", "Feminine Hygiene", 85, 95, "18 pads", _ALL),
    ("Himalaya baby powder", "Himalaya", "Baby Care", 125, 140, "200 g", _ALL),
    ("Vicks vaporub", "Vicks", "Health & Pharma", 89, 99, "25 ml", _ALL),
    ("i-Pill emergency contraceptive", "Cipla", "Sexual Wellness", 110, 125, "1 tab", _ALL),
    ("Ariel matic top load", "Ariel", "Cleaners & Repellents", 299, 329, "2 kg", _ALL),
    ("All out ultra refill", "All Out", "Cleaners & Repellents", 85, 95, "1 pc", _ALL),
    ("Scotch-Brite scrub pad", "Scotch-Brite", "Cleaners & Repellents", 45, 50, "3 pcs", _ALL),
    ("Ambipur car freshener", "Ambipur", "Cleaners & Repellents", 299, 349, "1 pc", _ALL),
    ("Syska 12W LED panel light", "Syska", "Electronics", 349, 399, "1 pc", _ALL),
    ("boAt Rockerz 450 headphones", "boAt", "Electronics", 1499, 1990, "1 pc", _ALL),
    ("Pilot V5 pen blue", "Pilot", "Stationery & Games", 65, 70, "1 pc", _ALL),
    ("Jenga classic game", "Hasbro", "Stationery & Games", 899, 999, "1 pc", _ALL),
    ("Lego classic bricks medium", "Lego", "Toy Store", 2499, 2799, "1 box", ["Delhi NCR"]),
    ("Ruskin Bond collection", "Puffin", "Book Store", 350, 399, "1 pc", _ALL),
    ("Kundan necklace set", "Zaveri", "Jewellery Store", 799, 899, "1 set", _ALL),
    ("Van Heusen innerwear vest", "Van Heusen", "Fashion Basics", 349, 399, "2 pcs", _ALL),
    ("Cosco tennis ball 3 pack", "Cosco", "Sports Store", 249, 279, "3 pcs", _ALL),
    ("Domestic sewing kit", "Fab N Sew", "Hobby Store", 99, 120, "1 kit", _ALL),
    ("American Tourister duffel bag", "American Tourister", "Travel Store", 1299, 1499, "1 pc", _ALL),
    ("Himalaya Liv.52 tablets", "Himalaya", "Pharma Store", 165, 180, "100 tabs", _ALL),
    ("Magnum almond ice cream", "Kwality Walls", "Ice Cream Store", 90, 95, "1 pc", _ALL),
    ("Wicks for diyas cotton", "Local", "Spiritual Needs", 25, 30, "1 pack", _ALL),
    ("Pooja oil mustard small", "Local", "Spiritual Needs", 45, 55, "200 ml", _ALL),
    ("Gift box empty medium", "Archies", "E-Gifts Store", 199, 249, "1 pc", _ALL),
    ("Pet bowl double diner", "Savic", "Pet Store", 349, 399, "1 pc", _ALL),
    ("Dog treat chicken strips", "Pedigree", "Pet Store", 199, 229, "200 g", _ALL),
    ("Paan flavoured mouth spray", "Spraymintt", "Paan Corner", 75, 85, "1 pc", _ALL),
    ("Amul Lactose Free milk", "Amul", "Dairy, Bread & Eggs", 62, 65, "1 L", ["Delhi NCR"]),
    ("Lactose free curd cup", "Epigamia", "Dairy, Bread & Eggs", 55, 60, "150 g", ["Delhi NCR"]),
    ("Sourdough burger buns", "The Baker's Dozen", "Bakery & Biscuits", 99, 110, "4 pcs", ["Delhi NCR"]),
    ("Granola honey almond", "True Elements", "Dry Fruits & Cereals", 299, 349, "400 g", _ALL),
    ("Protein bar peanut butter", "RiteBite", "Dry Fruits & Cereals", 89, 99, "1 pc", _ALL),
    ("Tata Sampann rock salt", "Tata Sampann", "Oil, Ghee & Masala", 45, 50, "1 kg", _ALL),
    ("Organic honey raw", "Dabur", "Dry Fruits & Cereals", 249, 275, "500 g", _ALL),
    ("Fresh coriander bunch", "Fresh", "Vegetables & Fruits", 15, 20, "1 bunch", _ALL),
    ("Ginger adrak", "Fresh", "Vegetables & Fruits", 35, 40, "250 g", _ALL),
    ("Green chilli", "Fresh", "Vegetables & Fruits", 12, 15, "100 g", _ALL),
    ("Lady finger bhindi", "Fresh", "Vegetables & Fruits", 38, 45, "500 g", _ALL),
    ("Brinjal baingan", "Fresh", "Vegetables & Fruits", 32, 38, "500 g", _ALL),
    ("Cabbage patta gobhi", "Fresh", "Vegetables & Fruits", 28, 35, "1 pc", _ALL),
    ("Spinach palak bunch", "Fresh", "Vegetables & Fruits", 22, 28, "1 bunch", _ALL),
    ("Mushroom button", "Fresh", "Vegetables & Fruits", 59, 69, "200 g", _ALL),
    ("Pomegranate anar", "Fresh", "Vegetables & Fruits", 89, 99, "2 pcs", _ALL),
    ("Papaya raw", "Fresh", "Vegetables & Fruits", 45, 55, "1 kg", _ALL),
    ("Watermelon kiran", "Fresh", "Vegetables & Fruits", 69, 79, "1 kg", _ALL),
    ("Muskmelon", "Fresh", "Vegetables & Fruits", 55, 65, "1 pc", _ALL),
    ("Sweet corn cob", "Fresh", "Vegetables & Fruits", 35, 42, "2 pcs", _ALL),
    ("Beetroot chukandar", "Fresh", "Vegetables & Fruits", 38, 45, "500 g", _ALL),
    ("Radish mooli", "Fresh", "Vegetables & Fruits", 25, 30, "500 g", _ALL),
    ("Carrot orange", "Fresh", "Vegetables & Fruits", 48, 55, "500 g", _ALL),
    ("Capsicum green", "Fresh", "Vegetables & Fruits", 42, 50, "500 g", _ALL),
    ("French beans", "Fresh", "Vegetables & Fruits", 45, 52, "500 g", _ALL),
    ("Cluster beans guar", "Fresh", "Vegetables & Fruits", 35, 42, "500 g", _ALL),
    ("Drumstick moringa", "Fresh", "Vegetables & Fruits", 39, 45, "250 g", _ALL),
    ("Lemon nimbu", "Fresh", "Vegetables & Fruits", 28, 35, "500 g", _ALL),
    ("Raw mango kairi", "Fresh", "Vegetables & Fruits", 65, 75, "500 g", _ALL),
    ("Coconut fresh", "Fresh", "Vegetables & Fruits", 55, 65, "1 pc", _ALL),
    ("Pineapple", "Fresh", "Vegetables & Fruits", 79, 89, "1 pc", _ALL),
    ("Dragon fruit", "Fresh", "Vegetables & Fruits", 149, 169, "1 pc", ["Delhi NCR"]),
    ("Blueberry imported", "Fresh", "Vegetables & Fruits", 199, 229, "125 g", ["Delhi NCR"]),
    ("Cherry imported", "Fresh", "Vegetables & Fruits", 349, 399, "200 g", ["Delhi NCR"]),
    ("Zucchini green", "Fresh", "Vegetables & Fruits", 89, 99, "500 g", ["Delhi NCR"]),
    ("Asparagus bunch", "Fresh", "Vegetables & Fruits", 199, 229, "250 g", ["Delhi NCR"]),
    ("Leeks bunch", "Fresh", "Vegetables & Fruits", 129, 149, "1 bunch", ["Delhi NCR"]),
    ("Romaine lettuce", "Fresh", "Vegetables & Fruits", 99, 110, "1 pc", ["Delhi NCR"]),
    ("Arugula leaves", "Fresh", "Vegetables & Fruits", 149, 169, "100 g", ["Delhi NCR"]),
    ("Bok choy", "Fresh", "Vegetables & Fruits", 79, 89, "500 g", ["Delhi NCR"]),
    ("Thai basil", "Fresh", "Vegetables & Fruits", 49, 55, "1 bunch", ["Delhi NCR"]),
    ("Microgreens mix", "Fresh", "Vegetables & Fruits", 149, 175, "50 g", ["Delhi NCR"]),
    ("Edamame frozen", "Fresh", "Vegetables & Fruits", 199, 229, "400 g", ["Delhi NCR"]),
    ("Tofu firm block", "Nutriplus", "Instant Food", 89, 99, "200 g", _ALL),
    ("Soya chunks", "Nutrela", "Instant Food", 65, 72, "200 g", _ALL),
    ("Paneer fresh block", "Amul", "Dairy, Bread & Eggs", 89, 95, "200 g", _ALL),
    ("Greek yogurt strawberry", "Epigamia", "Dairy, Bread & Eggs", 65, 70, "130 g", _ALL),
    ("Lassi masala salted", "Amul", "Dairy, Bread & Eggs", 25, 28, "200 ml", _ALL),
    ("Buttermilk spiced", "Amul", "Dairy, Bread & Eggs", 20, 22, "200 ml", _ALL),
    ("Mozzarella cheese block", "Go", "Dairy, Bread & Eggs", 199, 225, "200 g", _ALL),
    ("Processed cheese cubes", "Amul", "Dairy, Bread & Eggs", 125, 135, "200 g", _ALL),
    ("Gouda cheese slices", "Go", "Dairy, Bread & Eggs", 249, 275, "200 g", ["Delhi NCR"]),
    ("Feta cheese in brine", "Go", "Dairy, Bread & Eggs", 299, 329, "200 g", ["Delhi NCR"]),
    ("Smoked salmon slices", "Licious", "Chicken, Meat & Fish", 499, 549, "100 g", ["Delhi NCR"]),
    ("Turkey ham slices", "Prasuma", "Chicken, Meat & Fish", 299, 329, "200 g", ["Delhi NCR"]),
    ("Lamb mince keema", "Licious", "Chicken, Meat & Fish", 349, 379, "500 g", ["Delhi NCR"]),
    ("Prawns cleaned deveined", "Licious", "Chicken, Meat & Fish", 399, 449, "250 g", _ALL),
    ("Basa fish fillet", "Fresh", "Chicken, Meat & Fish", 199, 229, "500 g", _ALL),
    ("Mutton curry cut", "Licious", "Chicken, Meat & Fish", 499, 549, "500 g", _ALL),
    ("Chicken breast boneless", "Licious", "Chicken, Meat & Fish", 249, 279, "450 g", _ALL),
    ("Turkey pepperoni", "Prasuma", "Chicken, Meat & Fish", 249, 279, "150 g", ["Delhi NCR"]),
    ("Plant based burger patty", "Blue Tribe", "Instant Food", 199, 229, "2 pcs", ["Delhi NCR"]),
    ("Vegan cheese block", "Plantaway", "Dairy, Bread & Eggs", 349, 399, "200 g", ["Delhi NCR"]),
    ("Oat milk barista edition", "Oatly", "Dairy, Bread & Eggs", 299, 329, "1 L", ["Delhi NCR"]),
    ("Almond milk unsweetened", "So Good", "Dairy, Bread & Eggs", 249, 275, "1 L", ["Delhi NCR"]),
    ("Coconut milk cooking", "Dabur", "Oil, Ghee & Masala", 89, 99, "400 ml", _ALL),
    ("Extra virgin olive oil", "Figaro", "Oil, Ghee & Masala", 499, 549, "500 ml", _ALL),
    ("Truffle oil drizzle", "Urban Platter", "Oil, Ghee & Masala", 699, 799, "100 ml", ["Delhi NCR"]),
    ("Balsamic vinegar", "Del Monte", "Sauces & Spreads", 299, 329, "250 ml", ["Delhi NCR"]),
    ("Sriracha hot sauce", "Huy Fong", "Sauces & Spreads", 349, 399, "435 ml", ["Delhi NCR"]),
    ("Tahini paste", "Urban Platter", "Sauces & Spreads", 299, 329, "300 g", ["Delhi NCR"]),
    ("Hummus classic", "Tabouleh", "Sauces & Spreads", 199, 229, "200 g", ["Delhi NCR"]),
    ("Pita bread 6 pack", "The Baker's Dozen", "Bakery & Biscuits", 99, 110, "6 pcs", ["Delhi NCR"]),
    ("Bagel plain 4 pack", "The Baker's Dozen", "Bakery & Biscuits", 149, 169, "4 pcs", ["Delhi NCR"]),
    ("Croissant butter", "The Baker's Dozen", "Bakery & Biscuits", 89, 99, "2 pcs", ["Delhi NCR"]),
    ("Sourdough bread loaf", "The Baker's Dozen", "Bakery & Biscuits", 149, 175, "400 g", ["Delhi NCR"]),
    ("Multigrain bread", "The Baker's Dozen", "Bakery & Biscuits", 129, 149, "400 g", ["Delhi NCR"]),
    ("Garlic bread frozen", "McCain", "Bakery & Biscuits", 99, 110, "200 g", _ALL),
    ("Pizza base 2 pack", "English Oven", "Bakery & Biscuits", 45, 50, "2 pcs", _ALL),
    ("Rusk cake", "Parle", "Bakery & Biscuits", 55, 60, "400 g", _ALL),
    ("Marie gold biscuits", "Britannia", "Bakery & Biscuits", 30, 35, "250 g", _ALL),
    ("Good day cashew cookies", "Britannia", "Bakery & Biscuits", 55, 60, "600 g", _ALL),
    ("Oreo chocolate cream", "Oreo", "Bakery & Biscuits", 30, 35, "137 g", _ALL),
    ("Hide & seek chocolate chip", "Parle", "Bakery & Biscuits", 55, 60, "400 g", _ALL),
    ("Monaco salted crackers", "Parle", "Bakery & Biscuits", 35, 40, "400 g", _ALL),
    ("Digestive biscuits", "Britannia", "Bakery & Biscuits", 45, 50, "400 g", _ALL),
    ("NutriChoice 5 grain", "Britannia", "Bakery & Biscuits", 55, 60, "250 g", _ALL),
    ("Little hearts biscuits", "Sunfeast", "Bakery & Biscuits", 30, 35, "150 g", _ALL),
    ("Milk bikis biscuits", "Britannia", "Bakery & Biscuits", 35, 40, "500 g", _ALL),
    ("50-50 sweet & salty", "Britannia", "Bakery & Biscuits", 30, 35, "150 g", _ALL),
    ("Treat orange cream", "Parle", "Bakery & Biscuits", 25, 28, "150 g", _ALL),
    ("Bourbon chocolate cream", "Britannia", "Bakery & Biscuits", 35, 40, "400 g", _ALL),
    ("Tiger krunch biscuits", "Britannia", "Bakery & Biscuits", 30, 35, "300 g", _ALL),
    ("Nice time coconut", "Britannia", "Bakery & Biscuits", 35, 40, "400 g", _ALL),
    ("Marie light biscuits", "Sunfeast", "Bakery & Biscuits", 30, 35, "250 g", _ALL),
    ("Krackjack sweet salty", "Parle", "Bakery & Biscuits", 35, 40, "400 g", _ALL),
    ("Jim Jam cream", "Britannia", "Bakery & Biscuits", 35, 40, "400 g", _ALL),
    ("Pure magic chocolate", "Sunfeast", "Bakery & Biscuits", 55, 60, "300 g", _ALL),
    ("Mom's magic cashew almond", "Sunfeast", "Bakery & Biscuits", 55, 60, "400 g", _ALL),
    ("Dark fantasy choco nut", "Sunfeast", "Bakery & Biscuits", 110, 125, "300 g", _ALL),
    ("Fabelle chocolate bar", "ITC", "Sweets & Chocolates", 199, 225, "121 g", _ALL),
    ("Amul chocolate bar fruit nut", "Amul", "Sweets & Chocolates", 55, 60, "150 g", _ALL),
    ("Munch max chocolate", "Nestle", "Sweets & Chocolates", 20, 20, "38 g", _ALL),
    ("Perk chocolate wafer", "Cadbury", "Sweets & Chocolates", 20, 20, "30 g", _ALL),
    ("5 Star chocolate bar", "Cadbury", "Sweets & Chocolates", 20, 20, "38 g", _ALL),
    ("Gems chocolate pack", "Cadbury", "Sweets & Chocolates", 20, 20, "18 g", _ALL),
    ("Munch nuts chocolate", "Nestle", "Sweets & Chocolates", 20, 20, "38 g", _ALL),
    ("BarOne chocolate", "Cadbury", "Sweets & Chocolates", 20, 20, "38 g", _ALL),
    ("Chomp caramel chocolate", "Cadbury", "Sweets & Chocolates", 10, 10, "18 g", _ALL),
    ("Eclairs toffee pack", "Parle", "Sweets & Chocolates", 45, 50, "380 g", _ALL),
    ("Melody toffee pack", "Parle", "Sweets & Chocolates", 45, 50, "380 g", _ALL),
    ("Kismi bar", "Parle", "Sweets & Chocolates", 45, 50, "380 g", _ALL),
    ("Pulse candy kachcha aam", "Pass Pass", "Sweets & Chocolates", 10, 10, "48 g", _ALL),
    ("Hajmola candy", "Dabur", "Sweets & Chocolates", 45, 50, "120 g", _ALL),
    ("Alpenliebe gold caramel", "Perfetti", "Sweets & Chocolates", 45, 50, "32 pcs", _ALL),
    ("Center fresh gum", "Perfetti", "Sweets & Chocolates", 45, 50, "32 pcs", _ALL),
    ("Happydent wave gum", "Perfetti", "Sweets & Chocolates", 45, 50, "32 pcs", _ALL),
    ("Orbit spearmint gum", "Wrigley", "Sweets & Chocolates", 45, 50, "32 pcs", _ALL),
    ("Chupa chups lollipop", "Perfetti", "Sweets & Chocolates", 10, 10, "1 pc", _ALL),
    ("Mentos roll mint", "Perfetti", "Sweets & Chocolates", 30, 35, "37.5 g", _ALL),
    ("Polo mint roll", "Nestle", "Sweets & Chocolates", 30, 35, "34 g", _ALL),
    ("Tic tac orange", "Ferrero", "Sweets & Chocolates", 45, 50, "12.5 g", _ALL),
    ("Kinder joy boy", "Ferrero", "Sweets & Chocolates", 45, 50, "1 pc", _ALL),
    ("Kinder bueno", "Ferrero", "Sweets & Chocolates", 85, 90, "43 g", _ALL),
    ("Nutella & Go", "Nutella", "Sweets & Chocolates", 99, 110, "52 g", _ALL),
    ("Sunfeast dark fantasy bourbon", "Sunfeast", "Bakery & Biscuits", 55, 60, "400 g", _ALL),
]
